version: "3"
services:
  app:
    build: .
    ports:
      - "1337:8080"
      - "7331:7331"
      - "5858:5858"
      - "9229:9229"
    volumes:
      - .:/home/app
      - reserved:/home/app/node_modules/
    entrypoint:
      - npm
      - run
volumes:
  reserved: